apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: luckynumbers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luckynumbers
      tier: backend-api
  template:
    metadata:
      labels:
        app: luckynumbers
        tier: backend-api
    spec:
      containers:
      - name: gettickets-server
        image: ticklemon5ter/luckynumbers-server-api
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "3000"
          - name: REDIS_URL
            value: redis://database:$(DATABASE_SERVICE_PORT)
          - name: BROKER_URL
            value: ws://websocket:$(WEBSOCKET_SERVICE_PORT)
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: luckynumbers
spec:
  type: NodePort
  selector:
    app: luckynumbers
    tier: backend-api
  ports:
    - port: 3000
      targetPort: 3000
