apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImRHbGphMnhsYlc5dU5YUmxjam8xTTA0MldHZDZkWGRRYURJNWMyVT0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE4LjA5LjMgKHdpbmRvd3MpIgoJfQp9
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
