apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: luckynumbers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luckynumbers
      tier: database
  template:
    metadata:
      labels:
        app: luckynumbers
        tier: database
    spec:
      containers:
      - name: redis
        image: redis:5
    # persisitent data volume in /data
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: luckynumbers
    tier: database
spec:
  type: NodePort
  selector:
    app: luckynumbers
    tier: database
  ports:
    - port: 6379
      targetPort: 6379
