apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  labels:
    app: luckynumbers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luckynumbers
      tier: mqtt
  template:
    metadata:
      labels:
        app: luckynumbers
        tier: mqtt
    spec:
      containers:
      - name: gettickets-server
        image: toke/mosquitto
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: websocket
  labels:
    app: luckynumbers
spec:
  type: NodePort
  selector:
    app: luckynumbers
    tier: mqtt
  ports:
    - port: 9001
      targetPort: 9001
