apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  labels:
    app: luckynumbers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luckynumbers
      tier: mqtt
  template:
    metadata:
      labels:
        app: luckynumbers
        tier: mqtt
    spec:
      containers:
      - name: gettickets-server
        image: eclipse-mosquitto:1.6
        resources:
          limits:
            cpu: 1
        ports:
        - containerPort: 9001
        - containerPort: 1883
        volumeMounts:
        - name: mosquitto-config-vol
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: mosquitto-config-vol
        configMap: 
          name: eclipse-mosquitto-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eclipse-mosquitto-config
data:
  mosquitto.conf: |-
    # use an entirely default config, other than:
    listener 9001
    protocol websockets

---
apiVersion: v1
kind: Service
metadata:
  name: websocket
  labels:
    app: luckynumbers
spec:
  type: NodePort
  selector:
    app: luckynumbers
    tier: mqtt
  ports:
    - port: 9001
      targetPort: 9001
